### ISSUE TITLE
Make the IP module work with the Masquerade module

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/ip#6]
Very often, especially while actively developing we have to switch to a regular user account via https://github.com/backdrop-contrib/masquerade, and unfortunately this module is registering our IP to a respective user's logs. I wonder is it possible to disregard registering an IP if an admin user is just switching to regular user's account using the Masquerade module?

**Comment by bugfolder** [comment]
This seems pretty straightforward to implement. The Masquerade module sets a `$_SESSION` variable when you're masquerading:

```
$_SESSION['masquerading'] = $uid;
```

and unsets it when you're not, so we could just check this variable before saving an IP address.

However, although it seems like the most common use case would be the one requested, I'm a little reluctant to just change the behavior to silently stop recording if a user is masquerading, and rather leave that an explicit choice of the user.

But then...it seems like the desired behavior would be not to prevent logging the IP address at all, but to instead log it to the correct user account. So maybe add code to `ip_tracker_user_save()` (or its callers) to detect whether masquerading is going on (via checking that session variable), and if it is, use the uid of the actual user, rather than the masquerading user.

**Comment by alanmels** [comment]
Not sure what's the best way, but we would be happy not to see admin IPs in regular users' logs regardless of the method used. Thank you for considering this!

**Comment by bugfolder** [comment]
I think I have a fix for this, but would like to check it. Can you describe a specific scenario (sequence of steps) that results in the IP address being logged in the wrong place? (Assuming, of course, that both IP and Masquerade module are enabled.)

**Comment by alanmels** [comment]
Very simple: just masquerade as a regular user, switch back, go to the user's IP log and see your own IP address.

**Comment by bugfolder** [comment]
@alanmels, I've added a PR https://github.com/backdrop-contrib/ip/pull/8 that (I think) fixes this. Would you try it out?

**Comment by alanmels** [comment]
Thanks for the quick actions. Unfortunately, the one on https://github.com/backdrop-contrib/ip/tree/6_support_masquerade didn't work for me. As you can see the top line before Masquerading as an ordinary user was showing 23 and right after Masquerading and switching back it incremented to 24 registering my IP address.

![first](https://github.com/backdrop-contrib/ip/assets/56604405/77a8eed5-dd72-4d4f-8d1d-3c0a9145658e)
![second](https://github.com/backdrop-contrib/ip/assets/56604405/d31e3fcd-15c5-4dca-9945-b11058ef4bdd)

**Comment by bugfolder** [comment]
OK, that's pretty puzzling, because it works perfectly well for me on a test site. When I masquerade as another user, then switch back, I get two visits recorded for the "real" user (the one doing the masquerading) and none in the user being masqueraded as.

Just to double-check, after you apply the patch, do you have a function `_ip_demasquerade()` defined in your codebase?

**Comment by alanmels** [comment]
My bad - turns out I had pulled the main repository. Everything is working expected, so please commit it. Thank a lot, @bugfolder!
